name: Deploy to owolet

on:
  push:
    branches: [ master ]

jobs:
  build:
   name: Deploy server
   runs-on: ubuntu-latest
   steps:
     - name: Connect, pull, and restart server
       uses: garygrossgarten/github-action-ssh@v0.4.3
       with:
        command: sh deploy.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
