name: Deploy to owolet

on:
  push:
    branches: [ master ]

jobs:
  build:
   name: Deploy server
   runs-on: ubuntu-latest
   steps:
     - name: Connect, pull, and restart server
       uses: fifsky/ssh-action@master
       with:
        command: sh deploy.sh
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
